config/routes.rb
Rails.application.routes.draw do
  #get 'users_details/index'
  get 'welcome/index'

#get 'beneficiaries/create', as: 'create'

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :welcome 

  resources :beneficiaries

  resources :managers

  resources :transactions do
    get 'generate_otp', on: :member
    get 'download', on: :member
  end

  resources :users_details do
    get 'verify',on: :member 
  end

  root 'welcome#index' 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
  #has_many :users, dependent: :destroy
  #has_one :manager, dependent: :destroy
end

app/models/bankname.rb
class Bankname < ApplicationRecord
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
   has_and_belongs_to_many :users, dependent: :destroy
end 

app/models/localaddress.rb
class Localaddress < Address
end

app/models/manager.rb
class Manager < ApplicationRecord
  #belongs_to :bank
end

app/models/permanentaddress.rb
class Permanentaddress < Address
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:timeoutable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  mount_uploader :documentimage, ImageUploader
  mount_uploader :userimage, ImageUploader

  has_many :addresses , dependent: :destroy
  has_one :localaddress,dependent: :destroy
  has_one :permanentaddress,dependent: :destroy

  accepts_nested_attributes_for :localaddress
  accepts_nested_attributes_for :permanentaddress

  has_one :account, dependent: :destroy

  #belongs_to :bank, dependent: :destroy

  after_create :assign_default_role, :generate_account

  has_and_belongs_to_many :beneficiaries, dependent: :destroy

  has_many :transactions, dependent: :destroy


  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

  def generate_account
    Account.create!(account_number: (SecureRandom.random_number(9e11) + 1e11).to_i, user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname,:lastname,:fathername,:mothername,:occupation,:fatheroccupation,:motheroccupation,:phonenumber,:aadharnumber,:pannumber,:documentimage,:userimage,:bankname,permanentaddress_attributes: [:houseno,:streetno,:area,:city,:state,:country,:pincode],localaddress_attributes: [:houseno,:streetno,:area,:city,:state,:country,:pincode]])
  end

  end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  
  def index
    @users = User.all.where(bankname: current_user.bankname)
    @managers = Bank.all
  end

  def new 
  end

  def create
    account_number = params[:account_number]
    account = Account.find_by_account_number(account_number)
    if account
      user = User.find(account.user_id)
      Bank.create(bankname: user.bankname,manager_name: user.firstname+" "+user.lastname)
      user.add_role("manager")
      redirect_to managers_path
    else
      flash[:alert] = "Account doesn't exists"
      redirect_to new_manager_path
    end
  end
  
end

app/controllers/users_details_controller.rb
class UsersDetailsController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def verify
    @user = User.find(params[:id])
    @user.update_columns(verify: true) if !@user.verify
    @user.update_columns(verify_by: current_user.firstname+" "+current_user.lastname)
    UserMailer.with(user: @user).verification_mail.deliver
    redirect_to users_details_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @users = User.all
  end

=begin  def show
    @user = User.find(params[:id])
  end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_details_helper.rb
module UsersDetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users_details/index.html.erb
<table id="users_table" class="table table-hover">
  <thead>
  <tr>
    <th>FirstName</th>
    <th>LastName</th>
    <th>PhoneNumber</th>
    <th>Email</th>
    <th>Show User</th>
    <th>Verify</th>>
  </tr>
</thead>


<tbody>
  <% @users.each do |user| %>
  
    <tr>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td><%= user.phonenumber %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Full Details",users_detail_path(user) %></td>

      <% if user[:verify] == true %>
        <td>Verified User</td>
      <% else %>
        <td class="text-danger">Unverified User</td>
      <% end %>
    </tr> 
  <% end %>
</tbody>

</table>

app/views/users_details/show.html.erb
<table class="table table-bordered">
  <tr>
    <th>User_id: </th>
    <td><%= @user.id %></td>
  </tr>
  <% if @user.verify==true %>
    <tr>
      <th>Account Number : </th>
      <td><%= @user.account.account_number %></td>
    </tr>
  <% end %>
  <tr>
    <th>Profile Photo: </th>
    <td><%= link_to image_tag(@user.userimage.url(:thumb).to_s),@user.userimage.url %></td>
  </tr>
  <tr>
    <th>FirstName: </th>
    <td><%= @user.firstname %></td>
  </tr>
  <tr>
    <th>LastName: </th>
    <td><%= @user.lastname %></td>
  </tr>
  <tr>
    <th>FatherName: </th>
    <td><%= @user.fathername %></td>
  </tr>
  <tr>
    <th>MotherName: </th>
    <td><%= @user.mothername %></td>
  </tr>
  <tr>
    <th>Occupation: </th>
    <td><%= @user.occupation %></td>
  </tr>
  <tr>
    <th>FatherOccupation: </th>
    <td><%= @user.fatheroccupation %></td>
  </tr>
  <tr>
    <th>MotherOccupation: </th>
    <td><%= @user.motheroccupation %></td>
  </tr>
  <tr>
    <th>PhoneNumber: </th>
    <td><%= @user.phonenumber %></td>
  </tr>
  <tr>
    <th>Email: </th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>AadharNumber: </th>
    <td><%= @user.aadharnumber %></td>
  </tr>
  <tr>
    <th>Pan Number: </th>
    <td><%= @user.pannumber %></td>
  </tr>
  <tr>
    <th>Document Image: </th>
    <td><%= link_to image_tag(@user.documentimage.url(:thumb).to_s), @user.documentimage.url %></td>
  </tr>
  <tr>
    <th>BankName: </th>
    <td><%= @user.bankname %></td>
  </tr>
  <tr>
    <th>Permanent Address:</th>
    <td><%= @user.permanentaddress.houseno.+","+@user.permanentaddress.streetno+" "+@user.permanentaddress.area+",("+@user.permanentaddress.state+") Pincode : "+@user.permanentaddress.pincode.to_s %></td>
  </tr>
  <tr>
    <th>Local Address:</th>
    <td><%= @user.localaddress.houseno.+","+@user.localaddress.streetno+" "+@user.localaddress.area+",("+@user.localaddress.state+") Pincode : "+@user.localaddress.pincode.to_s %></td>
  </tr>

</table>

<% if (@user.verify == nil || @user.verify == false) %>
  <%= link_to 'Verify',verify_users_detail_path,class: "btn btn-success" %>
<% else %>
  <p>Verified User </p>
  <%= link_to 'View User Transactions',transactions_path %>
<% end %>