config/routes.rb
Rails.application.routes.draw do
  #get 'users_details/index'
  get 'welcome/index'

#get 'beneficiaries/create', as: 'create'

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :welcome 

  resources :beneficiaries

  resources :managers

  resources :transactions do
    get 'generate_otp', on: :member
    get 'download', on: :member
  end

  resources :users_details do
    get 'verify',on: :member 
  end

  root 'welcome#index' 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
  #has_many :users, dependent: :destroy
  #has_one :manager, dependent: :destroy
end

app/models/bankname.rb
class Bankname < ApplicationRecord
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
   has_and_belongs_to_many :users, dependent: :destroy
end 

app/models/localaddress.rb
class Localaddress < Address
end

app/models/manager.rb
class Manager < ApplicationRecord
  #belongs_to :bank
end

app/models/permanentaddress.rb
class Permanentaddress < Address
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:timeoutable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  mount_uploader :documentimage, ImageUploader
  mount_uploader :userimage, ImageUploader

  has_many :addresses , dependent: :destroy
  has_one :localaddress,dependent: :destroy
  has_one :permanentaddress,dependent: :destroy

  accepts_nested_attributes_for :localaddress
  accepts_nested_attributes_for :permanentaddress

  has_one :account, dependent: :destroy

  #belongs_to :bank, dependent: :destroy

  after_create :assign_default_role, :generate_account

  has_and_belongs_to_many :beneficiaries, dependent: :destroy

  has_many :transactions, dependent: :destroy


  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

  def generate_account
    Account.create!(account_number: (SecureRandom.random_number(9e11) + 1e11).to_i, user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname,:lastname,:fathername,:mothername,:occupation,:fatheroccupation,:motheroccupation,:phonenumber,:aadharnumber,:pannumber,:documentimage,:userimage,:bankname,permanentaddress_attributes: [:houseno,:streetno,:area,:city,:state,:country,:pincode],localaddress_attributes: [:houseno,:streetno,:area,:city,:state,:country,:pincode]])
  end

  end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  
  def index
    @users = User.all.where(bankname: current_user.bankname)
    @managers = Bank.all
  end

  def new 
  end

  def create
    account_number = params[:account_number]
    account = Account.find_by_account_number(account_number)
    if account
      user = User.find(account.user_id)
      Bank.create(bankname: user.bankname,manager_name: user.firstname+" "+user.lastname)
      user.add_role("manager")
      redirect_to managers_path
    else
      flash[:alert] = "Account doesn't exists"
      redirect_to new_manager_path
    end
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions_credited = Transaction.all.where(account_id: current_user.account.id)
    @transactions_debited = current_user.transactions

    @transactions = @transactions_credited.or(@transactions_debited)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    to_account_number = params[:transaction].values[0] 
    amount = params[:transaction].values[1].to_i
    to_account = Account.find_by_account_number(params[:transaction].values[0])
    to_account_user = User.find(to_account.user_id)
    beneficiary_exist = current_user.beneficiaries.where(account_number: to_account_number).first

    if (beneficiary_exist && current_user.account.otp == params[:transaction].values[2].to_i)
      to_account.update_columns(balance: (to_account.balance.to_i + amount))
      current_user.account.update_columns(balance: (current_user.account.balance.to_i - amount),otp: nil)
      Transaction.create(user_id: current_user.id,account_id: to_account.id,amount: amount)
      TransactionMailer.amount_credited(to_account_user,amount).deliver
      TransactionMailer.amount_debited(current_user,amount).deliver
      redirect_to transactions_path
    else
      flash[:alert] = "Invalid Otp or Beneficiary doesn't exixts"
      redirect_to new_transaction_path
    end
  end

  def generate_otp
    otp = SecureRandom.random_number(9e3).to_i
    @account = Account.find(params[:id])
    @account.update_columns(otp: otp)
    TransactionMailer.send_otp(current_user, otp).deliver
    
    respond_to do |format|
      format.js
    end
  end

  def download
    index
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TransactionPdf.new(@transactions,current_user)
        send_data pdf.render,
                  filename: "transaction",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

end

 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @users = User.all
  end

=begin  def show
    @user = User.find(params[:id])
  end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_details_helper.rb
module UsersDetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/transactions/index.html.erb
<h1>Transaction Index Page</h1>

<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Account Number</th>
    <th>Transaction Type</th>
    <th>Amount</th>
  </tr>

  <% @transactions.all.each do |transaction| %>
    <tr>
      <td><%= transaction.created_at.strftime("%m/%d/%y--%H:%M:%S") %></td>
      <% if transaction.account_id==current_user.account.id %>
        <td><%= transaction.user.account.account_number %></td>
        <td>Credit</td>
      <% else %>
        <td><%= transaction.account.account_number %></td>
        <td>Debit</td>
      <% end %>
      <td><%= transaction.amount %></td>
    </tr>
  <% end %>
</table>

<h5>Available Balance : <%= current_user.account.balance %> Rs.</h5>


<%= link_to 'Download Mini Statement', download_transaction_path(@transactions,format: 'pdf') ,class: "btn btn-info" %>

app/views/transactions/new.html.erb
<h1>Transaction</h1>

<div class="col-md-4">

  <%= form_with model: @transaction  do |f| %>
    <div class="field form-group">
      <%= f.label "To Account Number" %>
      <%= f.collection_select(:to_account_number, current_user.beneficiaries.all, :account_number,:account_number, :include_blank => "Please select beneficiary") %>
    </div>

    <div class="field form-group">
      <%= f.label "Enter Amount" %>
      <%= f.text_field :amount, class: "form-control",autofocus: true %>
    </div>

    <div class="field form-group">
      <%= f.text_field :otp , disabled: true,class: "form-control" %>
      <%= link_to "Generate OTP",generate_otp_transaction_path(current_user.account),remote: true, class: "btn btn-danger" %>
    </div>

    <div class="field form-group">
      <%= f.submit "Transfer",id: "verify",disabled: true ,class: "form-control btn btn-success"%>
    </div>

  <% end %>

</div>

app/views/welcome/index.html.erb
<% if (current_user.has_role? "user")&&(current_user[:verify] == nil)  %>
  <center>
    <h1>
      <u>Welcome <%= current_user.firstname+" "+current_user.lastname %>To NetBanking System</u>
    </h1>
    <hr>
      <p> Your Account Is on Hold </p>
      <p> Need to be verified by Bank Manager </p>
      <p>Regards</p>
      <p><%= current_user.bankname %>,BankManager</p>
    </center>

<% elsif current_user.has_role? "admin" %>  
  <br><h1>Welcome Admin! <%= current_user.firstname+" "+current_user.lastname %></h1>
<% else %>
  <center>
    <h1><u>Welcome Manager! <%= current_user.firstname+" "+current_user.lastname %> of <%= current_user.bankname %> Bank</u></h1>
  </center>
  <ul>
    <li>Verify User </li>
    <li>View User Details </li>
  </ul>
<% end %>