config/routes.rb
Rails.application.routes.draw do
  #get 'users_details/index'
  get 'welcome/index'

#get 'beneficiaries/create', as: 'create'

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :welcome 

  resources :beneficiaries

  resources :managers

  resources :transactions do
    get 'generate_otp', on: :member
    get 'download', on: :member
  end

  resources :users_details do
    get 'verify',on: :member 
  end

  root 'welcome#index' 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
  #has_many :users, dependent: :destroy
  #has_one :manager, dependent: :destroy
end

app/models/bankname.rb
class Bankname < ApplicationRecord
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
   has_and_belongs_to_many :users, dependent: :destroy
end 

app/models/localaddress.rb
class Localaddress < Address
end

app/models/manager.rb
class Manager < ApplicationRecord
  #belongs_to :bank
end

app/models/permanentaddress.rb
class Permanentaddress < Address
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:timeoutable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  mount_uploader :documentimage, ImageUploader
  mount_uploader :userimage, ImageUploader

  has_many :addresses , dependent: :destroy
  has_one :localaddress,dependent: :destroy
  has_one :permanentaddress,dependent: :destroy

  accepts_nested_attributes_for :localaddress
  accepts_nested_attributes_for :permanentaddress

  has_one :account, dependent: :destroy

  #belongs_to :bank, dependent: :destroy

  after_create :assign_default_role, :generate_account

  has_and_belongs_to_many :beneficiaries, dependent: :destroy

  has_many :transactions, dependent: :destroy


  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

  def generate_account
    Account.create!(account_number: (SecureRandom.random_number(9e11) + 1e11).to_i, user_id: self.id)
  end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  
  def index
    @users = User.all.where(bankname: current_user.bankname)
    @managers = Bank.all
  end

  def new 
  end

  def create
    account_number = params[:account_number]
    account = Account.find_by_account_number(account_number)
    if account
      user = User.find(account.user_id)
      Bank.create(bankname: user.bankname,manager_name: user.firstname+" "+user.lastname)
      user.add_role("manager")
      redirect_to managers_path
    else
      flash[:alert] = "Account doesn't exists"
      redirect_to new_manager_path
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @users = User.all
  end

=begin  def show
    @user = User.find(params[:id])
  end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_details_helper.rb
module UsersDetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetBanking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-inverse bg-light">
    <% if user_signed_in? %>
      <%= link_to 'Edit profile', edit_user_registration_path %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% if (current_user.has_role? "user")&&(current_user[:verify] == true )%>
        <%= link_to 'Add Beneficiary', new_beneficiary_path %>
        <%= link_to 'View Transactions',transactions_path %>
        <%= link_to 'View Beneficiaries', beneficiaries_path %>
        <%= link_to 'Fund Transfer', new_transaction_path %>
      <% end %>
      <% if current_user.has_role?("admin")%>
        <%= link_to "View Users Details",users_details_path %>
        <%= link_to "Create Manager",new_manager_path %>
        <%= link_to "View Managers", managers_path %>
      <%end%>
      <% if current_user.has_role?("manager")%>
        <%= link_to "View Users Details",users_details_path %>
      <% end %>

    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> 
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </nav>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>